apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-java-app-rest-dev
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: sample-java-app/environments/sample-java-app/overlays/dev
    repoURL: https://github.com/fn-javaapp/multi-tenancy-gitops-apps.git
    targetRevision: master
  # helm:
  #    valueFiles:
  #    - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true