apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgDPdCt6G7SJHpGszvVoSy+cm+y1NkSchcvwu8+NSTQjh2pomLnVtP08Rv8cJu+HKbPneUj7zPoNBQZcMYqXLDjhlg6nQh1iz6C55MIN3C1iDXVNZ1fQujSvizh/sJFWlgFgkQKQU6dc8PpOO0uYYcechlB4k22mDetvvBJ6mkNk5qLpBJFUqHZVA5cusyAkijM+0VvZGkmqLYDBUorDbGR/kGYKPUgDTws6K94oVYJNspU3uADZQq9+i4ekqG21BJ1d3KOyYgVi3I3rUQ3kKzO1+xdzudjTONlQbR94EQV+sZj/k6eG1ctLTfRU9lxvzm/j95Fl/vKqTFOtTilb/d2zP9JyU45dnXnTZOCuauhME1OsDpo3WP4vgoeHkPUHQNRQ+hx52wax3XdWkk/1b8+3w/1RQEhEGqm2CBKr0g+mX5Iz/T6aWtR/zC1cCcVccwOGmctG+Td0ZmbGDH2wC574VvgGlFESzT+TCXTUWd30jdb+eW+bq3hoyllw3rzfi+h5SZyTgqVJK1zbUQFw+gDVcCmIBKE/h2FaLRB34MEB/LwchMhCJ2BCES3GAtIvEGvJF0HJ/LcDyfd4IBLfpwJqUvvHfRN5cEjtDfC3hgxyV6TF+MiCVrxL52Tr9vNs4hYJXlLHF8DB8RRcMdhol+eaOhWmgn779n2K36PjEeuU4UYCYK1Fb76UjCDDeqUJtKxiYE+A1VIgpVeGyq7lodU1n89zJQuBRc6wVjR+aoxZEjZRl+I11vDV
    username: AgCHpUdz3UugPswc1/kY/VWVp5dxR3dORIHmiLT0TDL203MbZAq2IvR47Zc7qrSX9J8j+lY38l3DemhgHmzpZUpESjrpA2wPWG2TmgJNet6giXI/ACfR9s10uTz+gh818aXCGxFKP0lkaZs0hclKUcBNnWShTTOqrIhTimGfK2dzw+TqrmjXIkt4/9nfEmHSxtRynkgpEIT/7DKFC/3X1cAXbd6O8wS3haPnCKd3dtM80BrtOePBFj0i1Tb43KGCPi+iMGEa1Xmvq6loRxYcOm/4bo3AEDDKiTvSg6nw8uQi8LuI69g89CRQTeBstIoSXsioYTGCJMLqS4qJ3MzYOelyAbhyQrGxHS+wEcTwH+I391ecHiyqD2HuzQ2wEw2ZZdzgyDA9poSgmJMRYctTkZBlmGv7R76xg3k7GrlsxeSSOgDMla22pTtVstrxKuGfWTATdM3uoA+usm4LIIpx5IrQoEPGuMoFlCZSbHrZo/hYQNjYazkTZnM0yvMlP1mUgK+W48NZPrl7u7luMQPMFIdU8Ez2+Q8XfyOfis4muEvFcCiTTJF+92Nl0xyCRF/j2KkVFfPV89FH43H2RFErSS7MmCaxyCb23DRFMDO8AQzZjn89lPzKh8+8AesTIYYJJzvtaDHECW5jpMFC5ARgyH6HMiqJ91d6odtMVRUT8Zs9ugk+oaGtBdHockGpTb+FwJquUz1yJZIrxg==
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

