apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgDIec+BJqZGxK0mXMVZd7ib2At88yuzN7G2I3XWeRNHlQEroTwNrlxzBf0bcuEpujluL0vNWv6WH/q1z9SSxt4Eok+UBFvh5bvFqYQE5Igo9JU79bUbLFZkWYNRPt+lDYW1nm9wBL351vcmnADbAjjkkSvN2CaYl5U9DnuBD8RRwvi1NidGrK6CvT6mYGlURFrlXOlGAHgbGSrzAMH4HwiifrrOgwbvPJCFdyn6Ru2dYk+kbsD5U9qrKKRmyLmzpf+JsweQfHFU7OV0uvMaD4TCSawGss7J9lrvRZPyt0NML1niX6dZ+cAUWpVoEspgoXKih3z6Hhjn3gLTklc038PizX9a7+kn+zXTd1G/xSPoiQ38sdvTMRMvwCfsH1wAiwhfzgEiMwvfriAabtdw+FLptbMPhDYbIuJWxRCzpM6I35ZAQLgbYylplJ0mdEp3sAzC93dV5qO5hXHVRHvXqtFIk/GrmFer15vOqJe5MkrezOzk39JoD5TlOc7a9RJkyGMvij0T1NjffPEjz0KHAMeKzYfkhWkk1Dqvp2MMuQSo9Xo5fIrhdYD3FoSlsHsgVZ1Gg+LsCaXfykNAXu9+PShQPBE2Lb7vNG2zHNZdcIEBt5+2cK5oW5jlX7+k6XSEEVH86OZ52j3yTJ3RkII7snbbjBYIHSaMkX2Fgp+RhvqTTtk54KFD3/KC/ZVq+1SF1QiHCCv8WKPiBtWgfwEKrt2LhL9Fxs07MAHF3XAFDKif13foTiwFf/3+
    username: AgATt7nQoRbQDjuu2rQzDObsEJQFxHJClTjRwyY3m4XA1FSyX+foieYtfWyY5C9xnU2b6SrAnluDqGS8GEkoOMHkrquTu/w0jlbAokOYPPUlyWQCQKqZENRwNPL0SlWMYY9VyEoPOVwkHV1gDaGDhaAPuIx56ZU7n8gmepKY+ACguzluRLHjJRWZvqlk3j/DtsqwdRv2PV2uYiCHiyMSFI37EeFY4KqlHpEdX72rtovQB3HO7YrFkWp+8XwMxXpf1LXy+16kDPh6t9rHjkkT52+BuPWLSJk4qy6Op4P2BmiahSIzg52aol5auLBHIpfvYcxK9HoIICiEMKIumzGMokJ+L9qgwaZnwnJoZI8sTZkFfZ7TGT2qqkYQ1kU2XWdwikQW9bmnmRaHWty8I5eeczzXoocd3GftO1i2IeX3v2URIihPmYrUz5C1e/a70a66yAHLI2ZeZ3Rxeme4nbpSoSKzypCrjwheruTNE4ooF4hbAWbdKdIXwCGsYyxVRmswJAPGkZcpnpBSWNy3Pv5zk2vD053o3BpGHD5jZrRn6PhcJHsysG/ELJ+Xezkm6dqJVVlDSd4zvheJwdHsh+gsgR4a7phgpCehAs2BRT93PUMhP2Z9/rQzGazvDZLbSdl3F+fUegLlRGX4qgc3aQFsDSqaAxkKCGwesC13kr5bQobXmLiuFnVsigViFamr+ZeUyFO/LevgwF3ERw==
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

